name: Pull Requests

on:
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - '**.md'
    branches:
      - main

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@v1
    secrets: inherit
    with:
      charmcraft-channel: latest/stable
